# Generated by Django 5.1 on 2024-09-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractBlockchain',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contract.contract')),
                ('blockchainaddress', models.CharField(max_length=100)),
                ('hash_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractfile',
        ),
        migrations.AddField(
            model_name='contract',
            name='contractfileipfs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tender', to='tender.tender'),
        ),
    ]
