# Generated by Django 5.1 on 2024-09-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractblockchain_remove_contract_contractfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmeragreed', models.BooleanField(default=False)),
                ('buyeragreed', models.BooleanField(default=False)),
                ('deploy_status', models.BooleanField(default=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_contract', to='contract.contract')),
            ],
        ),
    ]
