# Generated by Django 5.1 on 2024-09-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contractdeliverystatus'),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_hash',
        ),
        migrations.RemoveField(
            model_name='contractblockchain',
            name='hash_key',
        ),
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tender', to='tender.tender', unique=True),
        ),
    ]
