# Generated by Django 5.1 on 2024-09-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contract_contract_hash_and_more'),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tender', to='tender.tender'),
        ),
    ]
