# Generated by Django 5.1 on 2024-09-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdeliverystatus',
            name='payment_status',
        ),
    ]
