# Generated by Django 5.1 on 2024-09-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0007_remove_contractdeliverystatus_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
        ),
    ]
