# Generated by Django 5.1 on 2024-09-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default='pi_78989293900100101233', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(default='card', max_length=30),
            preserve_default=False,
        ),
    ]
